---
title: "CDR3 comparison"
author: "Nils Eling"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Clones/CDR3_comparison.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script studies the similarities of clone composition between different samples.

## Read in data

```{r}
library(plyr)
library(reshape2)
library(ggplot2)
library(cowplot)
library(pheatmap)
source("../../Functions/auxiliary.R")

# Read in mixcr mapping results - one chain per .txt file
all.files <- list.files("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Clones/Txt_files", full.names = TRUE)

# Read in normalized counts
norm <- read.table("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Data/NormCounts.txt", sep = "\t", header = TRUE)
libraries <- sapply(colnames(norm), function(n){unlist(strsplit(n, "_"))[4]})

# Remove low quality libraries
all.files <- grep(paste(libraries,collapse="|"), all.files, value=TRUE, ignore.case = TRUE)

# All files containing TRG
TRG.files <- all.files[grepl("TRG", all.files)]
TRD.files <- all.files[grepl("TRD", all.files)]
```

# TRG

## Collect top 10 expanded clones for each old library

```{r expansion}
# Find clones - old
Vg1_old_TRG_V1 <- topCDR3(all.files, top = 10, keywords = c("Vg1", "old", "TRG"), select = "TCRG-V1")
#Vg1_old_TRG_V3 <- topCDR3(all.files, top = 10, keywords = c("Vg1", "old", "TRG"), select = "TCRG-V3")
Vg4_Th1_old_TRG_V4 <- topCDR3(all.files, top = 10, keywords = c("Vg4", "old", "TRG", "Th1-"), select = "TCRG-V4")
Vg4_Th17_old_TRG_V4 <- topCDR3(all.files, top = 10, keywords = c("Vg4", "old", "TRG", "Th17-"), select = "TCRG-V4")
Vg6_old_TRG_V6 <- topCDR3(all.files, top = 10, keywords = c("Vg6", "old", "TRG"), select = "TCRG-V6")

# Find clones - young
Vg1_young_TRG_V1 <- topCDR3(all.files, top = 10, keywords = c("Vg1", "young", "TRG"), select = "TCRG-V1")
#Vg1_young_TRG_V3 <- topCDR3(all.files, top = 10, keywords = c("Vg1", "young", "TRG"), select = "TCRG-V3")
Vg4_Th1_young_TRG_V4 <- topCDR3(all.files, top = 10, keywords = c("Vg4", "young", "TRG", "Th1-"), select = "TCRG-V4")
Vg4_Th17_young_TRG_V4 <- topCDR3(all.files, top = 10, keywords = c("Vg4", "young", "TRG", "Th17-"), select = "TCRG-V4")
Vg6_young_TRG_V6 <- topCDR3(all.files, top = 10, keywords = c("Vg6", "young", "TRG"), select = "TCRG-V6")
```

## Visuailze Vg1 cells

```{r}
# Merge clones
cur_clones <- data.frame(na = unique(c(Vg1_old_TRG_V1$na, Vg1_young_TRG_V1$na)),
                         aa = c(Vg1_old_TRG_V1$aa, Vg1_young_TRG_V1$aa)[
                           match(unique(c(Vg1_old_TRG_V1$na, Vg1_young_TRG_V1$na)),
                                 c(Vg1_old_TRG_V1$na, Vg1_young_TRG_V1$na))
                         ])
rownames(cur_clones) <- cur_clones$na

c.names <- c(paste("Vg1_Th1-_old_TRG_V1", 
                   1:sum(grepl("Vg1_Th1-old", TRG.files)), 
                   sep =  "_"), 
                   paste("Vg1_Th1-_young_TRG_V1", 
                   1:sum(grepl("Vg1_Th1-young", TRG.files)), 
                   sep =  "_"))
cur_mat <- matrix(data = NA, ncol = length(c.names), 
              nrow = nrow(cur_clones))
colnames(cur_mat) <- c.names
rownames(cur_mat) <- cur_clones$na

for(i in c.names){
  cur_mat[,i] <- clones.fraction(all.files, i, cur_clones$na)
}
cur_mat <- cur_mat[order(rowMeans(cur_mat), decreasing = TRUE),]
rownames(cur_mat) <- paste(cur_clones[rownames(cur_mat),"na"],
                           cur_clones[rownames(cur_mat),"aa"], sep = ", ")

# Find old specific clones
cur_mat.old <- cur_mat[rowSums(cur_mat[,grepl("young", colnames(cur_mat))]) < 0.0001,]
cur_mat.old <- cur_mat.old[order(rowMeans(cur_mat.old), decreasing = TRUE),]

# Find young specific clones
cur_mat.young <- cur_mat[rowSums(cur_mat[,grepl("old", colnames(cur_mat))]) < 0.0001,]
cur_mat.young <- cur_mat.young[order(rowMeans(cur_mat.young), decreasing = TRUE),]

# Find shared clones
cur_mat.shared <- cur_mat[!(rownames(cur_mat) %in% 
                               c(rownames(cur_mat.old),
                                 rownames(cur_mat.young))),]
cur_mat.shared <- cur_mat.shared[order(rowMeans(cur_mat.shared), 
                                       decreasing = TRUE),]

# Visualize in form of heatmap
pdf("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Figures/Vg1_TRG_CDR3.pdf", 
    onefile = FALSE, width = 10, height = 10)
pheatmap(rbind(cur_mat.old, cur_mat.shared, cur_mat.young), 
         color = c("grey", colorRampPalette(c("white", "blue", "red"))(9999)),
         cluster_cols = FALSE, cluster_rows = FALSE, 
         breaks = seq(0, max(cur_mat), length.out = 10000), cellheight = 8, 
         fontsize = 7, gaps_row = c(nrow(cur_mat.old), nrow(cur_mat.old)+nrow(cur_mat.shared)))
dev.off()
```

## Visuailze Vg4 cells

```{r}
# Merge clones
cur_clones <- data.frame(na = unique(c(Vg4_Th1_old_TRG_V4$na,
                                       Vg4_Th1_young_TRG_V4$na,
                                       Vg4_Th17_old_TRG_V4$na,
                                       Vg4_Th17_young_TRG_V4$na)),
                         aa = c(Vg4_Th1_old_TRG_V4$aa,
                                Vg4_Th1_young_TRG_V4$aa,
                                Vg4_Th17_old_TRG_V4$aa,
                                Vg4_Th17_young_TRG_V4$aa)[
                           match(unique(c(Vg4_Th1_old_TRG_V4$na,
                                       Vg4_Th1_young_TRG_V4$na,
                                       Vg4_Th17_old_TRG_V4$na,
                                       Vg4_Th17_young_TRG_V4$na)),
                                 c(Vg4_Th1_old_TRG_V4$na,
                                       Vg4_Th1_young_TRG_V4$na,
                                       Vg4_Th17_old_TRG_V4$na,
                                       Vg4_Th17_young_TRG_V4$na))
                         ])
rownames(cur_clones) <- cur_clones$na

c.names <- c(paste("Vg4_Th1-_young_TRG_V4", 
                   1:sum(grepl("Vg4_Th1-young", TRG.files)), 
                   sep =  "_"),
             paste("Vg4_Th1-_old_TRG_V4", 
                   1:sum(grepl("Vg4_Th1-old", TRG.files)), 
                   sep =  "_"), 
             paste("Vg4_Th17-_young_TRG_V4", 
                   1:sum(grepl("Vg4_Th17-young", TRG.files)), 
                   sep =  "_"),
             paste("Vg4_Th17-_old_TRG_V4", 
                   1:sum(grepl("Vg4_Th17-old", TRG.files)), 
                   sep =  "_"))
cur_mat <- matrix(data = NA, ncol = length(c.names), 
              nrow = nrow(cur_clones))
colnames(cur_mat) <- c.names
rownames(cur_mat) <- cur_clones$na

for(i in c.names){
  cur_mat[,i] <- clones.fraction(all.files, i, cur_clones$na)
}
cur_mat <- cur_mat[order(rowMeans(cur_mat), decreasing = TRUE),]
rownames(cur_mat) <- paste(cur_clones[rownames(cur_mat),"na"],
                           cur_clones[rownames(cur_mat),"aa"], sep = ", ")

# Find Th1 young specific clones
cur_mat.young.Th1 <- cur_mat[rowSums(cur_mat[,grepl("Th1-_old", 
                              colnames(cur_mat))]) < 0.0001 &
                               rowSums(cur_mat[,grepl("Th17-_young", 
                              colnames(cur_mat))]) < 0.0001 &
                               rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.young.Th1 <- cur_mat.young.Th1[order(rowMeans(cur_mat.young.Th1),
                                             decreasing = TRUE),]

# Find Th1 old specific clones
cur_mat.old.Th1 <- cur_mat[rowSums(cur_mat[,grepl("Th1-_young", 
                                    colnames(cur_mat))]) < 0.0001 &
                             rowSums(cur_mat[,grepl("Th17-_old", 
                                    colnames(cur_mat))]) < 0.0001 &
                             rowSums(cur_mat[,grepl("Th17-_young", 
                                    colnames(cur_mat))]) < 0.0001,]
cur_mat.old.Th1 <- cur_mat.old.Th1[order(rowMeans(cur_mat.old.Th1), 
                                         decreasing = TRUE),]

# Find Th17 young specific clones
cur_mat.young.Th17 <- cur_mat[rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) < 0.0001 &
                                rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) < 0.0001 & 
                                rowSums(cur_mat[,grepl("Th1-_old", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.young.Th17 <- cur_mat.young.Th17[order(rowMeans(cur_mat.young.Th17),
                                             decreasing = TRUE),]

# Find Th17 old specific clones
cur_mat.old.Th17 <- cur_mat[rowSums(cur_mat[,grepl("Th17-_young",
                                    colnames(cur_mat))]) < 0.0001 & 
                              rowSums(cur_mat[,grepl("Th1-_old", 
                                    colnames(cur_mat))]) < 0.0001 &
                              rowSums(cur_mat[,grepl("Th1-_young",
                                    colnames(cur_mat))]) < 0.0001,]
cur_mat.old.Th17 <- cur_mat.old.Th17[order(rowMeans(cur_mat.old.Th17), 
                                         decreasing = TRUE),]

# Find Th17  specific clones
cur_mat.Th17 <- cur_mat[rowSums(cur_mat[,grepl("Th17-_young", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) < 0.0001 &
                          rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.Th17 <- cur_mat.Th17[order(rowMeans(cur_mat.Th17),
                                             decreasing = TRUE),]

# Find Th1  specific clones
cur_mat.Th1 <- cur_mat[rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th1-_old", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th17-_young", 
                              colnames(cur_mat))]) < 0.0001 &
                          rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.Th1 <- cur_mat.Th1[order(rowMeans(cur_mat.Th1),
                                             decreasing = TRUE),]

# Find shared clones
cur_mat.shared <- cur_mat[!(rownames(cur_mat) %in% 
                               c(rownames(cur_mat.old.Th1),
                                 rownames(cur_mat.young.Th1),
                                 rownames(cur_mat.old.Th17),
                                 rownames(cur_mat.young.Th17),
                                 rownames(cur_mat.Th1),
                                 rownames(cur_mat.Th17))),]
cur_mat.shared <- cur_mat.shared[order(rowMeans(cur_mat.shared), 
                                       decreasing = TRUE),]

# Visualize in form of heatmap
pdf("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Figures/Vg4_TRG_CDR3.pdf", 
    onefile = FALSE, width = 10, height = 10)
pheatmap(rbind(cur_mat.young.Th1, cur_mat.old.Th1, cur_mat.Th1,
               cur_mat.shared, cur_mat.Th17, cur_mat.young.Th17,
               cur_mat.old.Th17), 
         color = c("grey", colorRampPalette(c("white", "blue", "red"))(9999)),
         cluster_cols = FALSE, cluster_rows = FALSE, 
         breaks = seq(0, max(cur_mat), length.out = 10000), cellheight = 8, 
         fontsize = 7, gaps_row = c(3, 8, 12, 54, 57, 65))
dev.off()
```

## Visuailze Vg6 cells

```{r}
# Merge clones
cur_clones <- data.frame(na = unique(c(Vg6_old_TRG_V6$na, Vg6_young_TRG_V6$na)),
                         aa = c(Vg6_old_TRG_V6$aa, Vg6_young_TRG_V6$aa)[
                           match(unique(c(Vg6_old_TRG_V6$na, Vg6_young_TRG_V6$na)),
                                 c(Vg6_old_TRG_V6$na, Vg6_young_TRG_V6$na))
                         ])
rownames(cur_clones) <- cur_clones$na

c.names <- c(paste("Vg6_Th17-_young_TRG_V6", 
                   1:sum(grepl("Vg6_Th17-young", TRG.files)), 
                   sep =  "_"), 
                   paste("Vg6_Th17-_old_TRG_V6", 
                   1:sum(grepl("Vg6_Th17-old", TRG.files)), 
                   sep =  "_"))
cur_mat <- matrix(data = NA, ncol = length(c.names), 
              nrow = nrow(cur_clones))
colnames(cur_mat) <- c.names
rownames(cur_mat) <- cur_clones$na

for(i in c.names){
  cur_mat[,i] <- clones.fraction(all.files, i, cur_clones$na)
}
cur_mat <- cur_mat[order(rowMeans(cur_mat), decreasing = TRUE),]
rownames(cur_mat) <- paste(cur_clones[rownames(cur_mat),"na"],
                           cur_clones[rownames(cur_mat),"aa"], sep = ", ")

# Find old specific clones
cur_mat.old <- cur_mat[rowSums(cur_mat[,grepl("young", colnames(cur_mat))]) < 0.0001,]
cur_mat.old <- cur_mat.old[order(rowMeans(cur_mat.old), decreasing = TRUE),]

# Find young specific clones
cur_mat.young <- cur_mat[rowSums(cur_mat[,grepl("old", colnames(cur_mat))]) < 0.0001,]
cur_mat.young <- cur_mat.young[order(rowMeans(cur_mat.young), decreasing = TRUE),]

# Find shared clones
cur_mat.shared <- cur_mat[!(rownames(cur_mat) %in% 
                               c(rownames(cur_mat.old),
                                 rownames(cur_mat.young))),]


# Visualize in form of heatmap
pdf("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Figures/Vg6_TRG_CDR3.pdf", 
    onefile = FALSE, width = 10, height = 10)
pheatmap(rbind(cur_mat.old, cur_mat.shared, cur_mat.young), 
         color = c("grey", colorRampPalette(c("white", "blue", "red"))(9999)),
         cluster_cols = FALSE, cluster_rows = FALSE, 
         breaks = seq(0, max(cur_mat), length.out = 10000), cellheight = 8, 
         fontsize = 7, gaps_row = c(nrow(cur_mat.old), nrow(cur_mat.old)+nrow(cur_mat.shared)))
dev.off()
```

# TRD

## Collect top 10 expanded clones for each old library

```{r expansion}
# Find clones - old
Vg1_old_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg1", "old", "TRD"))
Vg4_Th1_old_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg4", "old", "TRD", "Th1-"))
Vg4_Th17_old_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg4", "old", "TRD", "Th17-"))
Vg6_old_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg6", "old", "TRD"))

# Find clones - young
Vg1_young_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg1", "young", "TRD"))
Vg4_Th1_young_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg4", "young", "TRD", "Th1-"))
Vg4_Th17_young_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg4", "young", "TRD", "Th17-"))
Vg6_young_TRD <- topCDR3(all.files, top = 10, keywords = c("Vg6", "young", "TRD"))
```

## Visuailze Vg1 cells

```{r}
# Merge clones
cur_clones <- data.frame(na = unique(c(Vg1_old_TRD$na, Vg1_young_TRD$na)),
                         aa = c(Vg1_old_TRD$aa, Vg1_young_TRD$aa)[
                           match(unique(c(Vg1_old_TRD$na, Vg1_young_TRD$na)),
                                 c(Vg1_old_TRD$na, Vg1_young_TRD$na))
                         ], stringsAsFactors = FALSE)
rownames(cur_clones) <- cur_clones$na

c.names <- c(paste("Vg1_Th1-_old_TRD_X", 
                   1:sum(grepl("Vg1_Th1-old", TRD.files)), 
                   sep =  "_"), 
                   paste("Vg1_Th1-_young_TRD_X", 
                   1:sum(grepl("Vg1_Th1-young", TRD.files)), 
                   sep =  "_"))
cur_mat <- matrix(data = NA, ncol = length(c.names), 
              nrow = nrow(cur_clones))
colnames(cur_mat) <- c.names
rownames(cur_mat) <- cur_clones$na

for(i in c.names){
  cur_mat[,i] <- clones.fraction(all.files, i, cur_clones$na)
}
cur_mat <- cur_mat[order(rowMeans(cur_mat), decreasing = TRUE),]
rownames(cur_mat) <- paste(cur_clones[rownames(cur_mat),"na"],
                           cur_clones[rownames(cur_mat),"aa"], sep = ", ")

# Find old specific clones
cur_mat.old <- cur_mat[rowSums(cur_mat[,grepl("young", colnames(cur_mat))]) < 0.0001,]
cur_mat.old <- cur_mat.old[order(rowMeans(cur_mat.old), decreasing = TRUE),]

# Find young specific clones
cur_mat.young <- cur_mat[rowSums(cur_mat[,grepl("old", colnames(cur_mat))]) < 0.0001,]
cur_mat.young <- cur_mat.young[order(rowMeans(cur_mat.young), decreasing = TRUE),]

# Find shared clones
cur_mat.shared <- cur_mat[!(rownames(cur_mat) %in% 
                               c(rownames(cur_mat.old),
                                 rownames(cur_mat.young))),]
cur_mat.shared <- cur_mat.shared[order(rowMeans(cur_mat.shared), 
                                       decreasing = TRUE),]

# Visualize in form of heatmap
pdf("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Figures/Vg1_TRD_CDR3.pdf", 
    onefile = FALSE, width = 10, height = 15)
pheatmap(rbind(cur_mat.old, cur_mat.shared, cur_mat.young), 
         color = c("grey", colorRampPalette(c("white", "blue", "red"))(9999)),
         cluster_cols = FALSE, cluster_rows = FALSE, 
         breaks = seq(0, max(cur_mat), length.out = 10000), cellheight = 8, 
         fontsize = 7, gaps_row = c(nrow(cur_mat.old), nrow(cur_mat.old)+nrow(cur_mat.shared)))
dev.off()
```

## Visuailze Vg4 cells

```{r}
# Merge clones
cur_clones <- data.frame(na = unique(c(Vg4_Th1_old_TRD$na,
                                       Vg4_Th1_young_TRD$na,
                                       Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na)),
                         aa = c(Vg4_Th1_old_TRD$aa,
                                Vg4_Th1_young_TRD$aa,
                                Vg4_Th17_old_TRD$aa,
                                Vg4_Th17_young_TRD$aa)[
                           match(unique(c(Vg4_Th1_old_TRD$na,
                                       Vg4_Th1_young_TRD$na,
                                       Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na)),
                                 c(Vg4_Th1_old_TRD$na,
                                       Vg4_Th1_young_TRD$na,
                                       Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na))
                         ])
rownames(cur_clones) <- cur_clones$na

c.names <- c(paste("Vg4_Th1-_young_TRD_X", 
                   1:sum(grepl("Vg4_Th1-young", TRD.files)), 
                   sep =  "_"),
             paste("Vg4_Th1-_old_TRD_X", 
                   1:sum(grepl("Vg4_Th1-old", TRD.files)), 
                   sep =  "_"), 
             paste("Vg4_Th17-_young_TRD_X", 
                   1:sum(grepl("Vg4_Th17-young", TRD.files)), 
                   sep =  "_"),
             paste("Vg4_Th17-_old_TRD_X", 
                   1:sum(grepl("Vg4_Th17-old", TRD.files)), 
                   sep =  "_"))
cur_mat <- matrix(data = NA, ncol = length(c.names), 
              nrow = nrow(cur_clones))
colnames(cur_mat) <- c.names
rownames(cur_mat) <- cur_clones$na

for(i in c.names){
  cur_mat[,i] <- clones.fraction(all.files, i, cur_clones$na)
}
cur_mat <- cur_mat[order(rowMeans(cur_mat), decreasing = TRUE),]
rownames(cur_mat) <- paste(cur_clones[rownames(cur_mat),"na"],
                           cur_clones[rownames(cur_mat),"aa"], sep = ", ")

# Find Th1 young specific clones
cur_mat.young.Th1 <- cur_mat[rowSums(cur_mat[,grepl("Th1-_old", 
                              colnames(cur_mat))]) < 0.0001 &
                               rowSums(cur_mat[,grepl("Th17-_young", 
                              colnames(cur_mat))]) < 0.0001 &
                               rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.young.Th1 <- cur_mat.young.Th1[order(rowMeans(cur_mat.young.Th1),
                                             decreasing = TRUE),]

# Find Th1 old specific clones
cur_mat.old.Th1 <- cur_mat[rowSums(cur_mat[,grepl("Th1-_young", 
                                    colnames(cur_mat))]) < 0.0001 &
                             rowSums(cur_mat[,grepl("Th17-_old", 
                                    colnames(cur_mat))]) < 0.0001 &
                             rowSums(cur_mat[,grepl("Th17-_young", 
                                    colnames(cur_mat))]) < 0.0001,]
cur_mat.old.Th1 <- cur_mat.old.Th1[order(rowMeans(cur_mat.old.Th1), 
                                         decreasing = TRUE),]

# Find Th17 young specific clones
cur_mat.young.Th17 <- cur_mat[rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) < 0.0001 &
                                rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) < 0.0001 & 
                                rowSums(cur_mat[,grepl("Th1-_old", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.young.Th17 <- cur_mat.young.Th17[order(rowMeans(cur_mat.young.Th17),
                                             decreasing = TRUE),]

# Find Th17 old specific clones
cur_mat.old.Th17 <- cur_mat[rowSums(cur_mat[,grepl("Th17-_young",
                                    colnames(cur_mat))]) < 0.0001 & 
                              rowSums(cur_mat[,grepl("Th1-_old", 
                                    colnames(cur_mat))]) < 0.0001 &
                              rowSums(cur_mat[,grepl("Th1-_young",
                                    colnames(cur_mat))]) < 0.0001,]
cur_mat.old.Th17 <- cur_mat.old.Th17[order(rowMeans(cur_mat.old.Th17), 
                                         decreasing = TRUE),]

# Find Th17  specific clones
cur_mat.Th17 <- cur_mat[rowSums(cur_mat[,grepl("Th17-_young", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) < 0.0001 &
                          rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.Th17 <- cur_mat.Th17[order(rowMeans(cur_mat.Th17),
                                             decreasing = TRUE),]

# Find Th1  specific clones
cur_mat.Th1 <- cur_mat[rowSums(cur_mat[,grepl("Th1-_young", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th1-_old", 
                              colnames(cur_mat))]) > 0.0001 &
                          rowSums(cur_mat[,grepl("Th17-_young", 
                              colnames(cur_mat))]) < 0.0001 &
                          rowSums(cur_mat[,grepl("Th17-_old", 
                              colnames(cur_mat))]) < 0.0001,]
cur_mat.Th1 <- cur_mat.Th1[order(rowMeans(cur_mat.Th1),
                                             decreasing = TRUE),]

# Find shared clones
cur_mat.shared <- cur_mat[!(rownames(cur_mat) %in% 
                               c(rownames(cur_mat.old.Th1),
                                 rownames(cur_mat.young.Th1),
                                 rownames(cur_mat.old.Th17),
                                 rownames(cur_mat.young.Th17),
                                 rownames(cur_mat.Th1),
                                 rownames(cur_mat.Th17))),]
cur_mat.shared <- cur_mat.shared[order(rowMeans(cur_mat.shared), 
                                       decreasing = TRUE),]

# Visualize in form of heatmap
pdf("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Figures/Vg4_TRD_CDR3.pdf", 
    onefile = FALSE, width = 10, height = 25)
pheatmap(rbind(cur_mat.young.Th1, cur_mat.old.Th1, cur_mat.Th1,
               cur_mat.shared, cur_mat.Th17, cur_mat.young.Th17,
               cur_mat.old.Th17), 
         color = c("grey", colorRampPalette(c("white", "blue", "red"))(9999)),
         cluster_cols = FALSE, cluster_rows = FALSE, 
         breaks = seq(0, max(cur_mat), length.out = 10000), cellheight = 8, 
         fontsize = 7, gaps_row = c(44, 78, 87, 98, 113, 147))
dev.off()
```

## Visuailze Vg6 cells

```{r}
# Merge clones
cur_clones <- data.frame(na = unique(c(Vg6_old_TRD$na, Vg6_young_TRD$na)),
                         aa = c(Vg6_old_TRD$aa, Vg6_young_TRD$aa)[
                           match(unique(c(Vg6_old_TRD$na, Vg6_young_TRD$na)),
                                 c(Vg6_old_TRD$na, Vg6_young_TRD$na))
                         ])
rownames(cur_clones) <- cur_clones$na

c.names <- c(paste("Vg6_Th17-_young_TRD_X", 
                   1:sum(grepl("Vg6_Th17-young", TRG.files)), 
                   sep =  "_"), 
                   paste("Vg6_Th17-_old_TRD_X", 
                   1:sum(grepl("Vg6_Th17-old", TRG.files)), 
                   sep =  "_"))
cur_mat <- matrix(data = NA, ncol = length(c.names), 
              nrow = nrow(cur_clones))
colnames(cur_mat) <- c.names
rownames(cur_mat) <- cur_clones$na

for(i in c.names){
  cur_mat[,i] <- clones.fraction(all.files, i, cur_clones$na)
}
cur_mat <- cur_mat[order(rowMeans(cur_mat), decreasing = TRUE),]
rownames(cur_mat) <- paste(cur_clones[rownames(cur_mat),"na"],
                           cur_clones[rownames(cur_mat),"aa"], sep = ", ")

# Find old specific clones
cur_mat.old <- cur_mat[rowSums(cur_mat[,grepl("young", colnames(cur_mat))]) < 0.0001,]
cur_mat.old <- cur_mat.old[order(rowMeans(cur_mat.old), decreasing = TRUE),]

# Find young specific clones
cur_mat.young <- cur_mat[rowSums(cur_mat[,grepl("old", colnames(cur_mat))]) < 0.0001,]
cur_mat.young <- cur_mat.young[order(rowMeans(cur_mat.young), decreasing = TRUE),]

# Find shared clones
cur_mat.shared <- cur_mat[!(rownames(cur_mat) %in% 
                               c(rownames(cur_mat.old),
                                 rownames(cur_mat.young))),]


# Visualize in form of heatmap
pdf("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Figures/Vg6_TRG_CDR3.pdf", 
    onefile = FALSE, width = 10, height = 15)
pheatmap(rbind(cur_mat.old, cur_mat.shared, cur_mat.young), 
         color = c("grey", colorRampPalette(c("white", "blue", "red"))(9999)),
         cluster_cols = FALSE, cluster_rows = FALSE, 
         breaks = seq(0, max(cur_mat), length.out = 10000), cellheight = 8, 
         fontsize = 7, gaps_row = c(nrow(cur_mat.old), nrow(cur_mat.old)+nrow(cur_mat.shared)))
dev.off()
```

