---
title: "Figure 3"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data and libraries

```{r libraries, message=FALSE}
library(plyr)
library(reshape2)
library(ggplot2)
library(cowplot)
library(pheatmap)
library(openxlsx)
library(readxl)
source("../Functions/auxiliary.R")

# Read in mixcr mapping results - one chain per .txt file
all.files <- list.files("../../../Dropbox (Cambridge University)/GammaDelta/Analysis/Clones/Txt_files", full.names = TRUE)

# Read in normalized counts
norm <- read.table("../../../Dropbox (Cambridge University)/GammaDelta/Analysis/Data/NormCounts.txt", sep = "\t", header = TRUE)
libraries <- sapply(colnames(norm), function(n){unlist(strsplit(n, "_"))[4]})

# Remove low quality libraries
all.files <- grep(paste(libraries,collapse="|"), all.files, value=TRUE, ignore.case = TRUE)

# All files containing TRG
TRG.files <- all.files[grepl("TRG", all.files)]
TRD.files <- all.files[grepl("TRD", all.files)]

# Since the annotation of delta chains is not very consistent, 
# we manually re-annotated the chains
# Chain annotation
annot <- as.data.frame(read_xls("../Data/Variable_sequences_to_edit.xls"))
annot$`IMGT sub-group`[is.na(annot$`IMGT sub-group`)] <- annot$names[is.na(annot$`IMGT sub-group`)]
rownames(annot) <- annot$names
```

# Clone diversity using the inverse simpsons index

## TCR gamma

### Vg1 Th1

```{r}
# Save dataframes in list 
inv.simps.list <- list()

cur_files <- TRG.files[grepl("Vg1_Th1-", TRG.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRG.files[grepl("Vg1_Th1-", TRG.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg1.Th1 <- data.frame(inv.Simps(cur_files, cur_names, select = "TCRG-V1", 
                                subsample = TRUE))
colnames(Vg1.Th1) <- "Inv_Simps"
Vg1.Th1$Age <- factor(sapply(rownames(Vg1.Th1), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg1.Th1$Replicate <- c(1:5, 1:6)

# Plot results
p.Vg1.Th1.gamma <- ggplot(Vg1.Th1) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 60)) + scale_fill_manual(values = c("white", "red")) + guides(fill=FALSE)
# Statistical test
t.test(Vg1.Th1[Vg1.Th1$Age == "young","Inv_Simps"],
       Vg1.Th1[Vg1.Th1$Age == "old","Inv_Simps"])

# Save in list
inv.simps.list[["TRG_Vg1_Th1"]] <- Vg1.Th1
```

### Vg4 Th1

```{r}
cur_files <- TRG.files[grepl("Vg4_Th1-", TRG.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRG.files[grepl("Vg4_Th1-", TRG.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg4.Th1 <- data.frame(inv.Simps(cur_files, cur_names, select = "TCRG-V4", 
                                subsample = TRUE))
colnames(Vg4.Th1) <- "Inv_Simps"
Vg4.Th1$Age <- factor(sapply(rownames(Vg4.Th1), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg4.Th1$Replicate <- c(1:4, 1:6)

# Plot results
p.Vg4.Th1.gamma <- ggplot(Vg4.Th1) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 60)) + scale_fill_manual(values = c("white", "red")) + guides(fill=FALSE)
# Statistical test
t.test(Vg4.Th1[Vg4.Th1$Age == "young","Inv_Simps"],
       Vg4.Th1[Vg4.Th1$Age == "old","Inv_Simps"])

# Save in list
inv.simps.list[["TRG_Vg4_Th1"]] <- Vg4.Th1
```

### Vg4 Th17

```{r}
cur_files <- TRG.files[grepl("Vg4_Th17-", TRG.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRG.files[grepl("Vg4_Th17-", TRG.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg4.Th17 <- data.frame(inv.Simps(cur_files, cur_names, select = "TCRG-V4", 
                                subsample = TRUE))
colnames(Vg4.Th17) <- "Inv_Simps"
Vg4.Th17$Age <- factor(sapply(rownames(Vg4.Th17), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg4.Th17$Replicate <- c(1:4, 1:6)

# Plot results
p.Vg4.Th17.gamma <- ggplot(Vg4.Th17) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 60)) + scale_fill_manual(values = c("white", "red")) + guides(fill=FALSE)
# Statistical test
t.test(Vg4.Th17[Vg4.Th17$Age == "young","Inv_Simps"],
       Vg4.Th17[Vg4.Th17$Age == "old","Inv_Simps"])

inv.simps.list[["TRG_Vg4_Th17"]] <- Vg4.Th17
```

### Vg6 Th17

```{r}
cur_files <- TRG.files[grepl("Vg6_Th17-", TRG.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRG.files[grepl("Vg6_Th17-", TRG.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg6.Th17 <- data.frame(inv.Simps(cur_files, cur_names, select = "TCRG-V6", 
                                subsample = TRUE))
colnames(Vg6.Th17) <- "Inv_Simps"
Vg6.Th17$Age <- factor(sapply(rownames(Vg6.Th17), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg6.Th17$Replicate <- c(1:6, 1:4)

# Plot results
p.Vg6.Th17.gamma <- ggplot(Vg6.Th17) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 2)) + scale_fill_manual(values = c("white", "red")) + guides(fill=FALSE)
# Statistical test
t.test(Vg6.Th17[Vg6.Th17$Age == "young","Inv_Simps"],
       Vg6.Th17[Vg6.Th17$Age == "old","Inv_Simps"])

# Save in list
inv.simps.list[["TRG_Vg6_Th17"]] <- Vg6.Th17
```

## TCR delta

### Vg1 Th1

```{r}
cur_files <- TRD.files[grepl("Vg1_Th1-", TRD.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRD.files[grepl("Vg1_Th1-", TRD.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg1.Th1 <- data.frame(inv.Simps(cur_files, cur_names, 
                                subsample = TRUE))
colnames(Vg1.Th1) <- "Inv_Simps"
Vg1.Th1$Age <- factor(sapply(rownames(Vg1.Th1), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg1.Th1$Replicate <- c(1:5, 1:6)

# Plot results
p.Vg1.Th1.delta <- ggplot(Vg1.Th1) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 500)) + scale_fill_manual(values = c("white", "red")) + guides(fill=FALSE)
# Statistical test
t.test(Vg1.Th1[Vg1.Th1$Age == "young","Inv_Simps"],
       Vg1.Th1[Vg1.Th1$Age == "old","Inv_Simps"])

# Save in list
inv.simps.list[["TRD_Vg1_Th1"]] <- Vg1.Th1
```

### Vg4 Th1

```{r}
cur_files <- TRD.files[grepl("Vg4_Th1-", TRD.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRD.files[grepl("Vg4_Th1-", TRD.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg4.Th1 <- data.frame(inv.Simps(cur_files, cur_names, 
                                subsample = TRUE))
colnames(Vg4.Th1) <- "Inv_Simps"
Vg4.Th1$Age <- factor(sapply(rownames(Vg4.Th1), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg4.Th1$Replicate <- c(1:4, 1:6)

# Plot results
p.Vg4.Th1.delta <- ggplot(Vg4.Th1) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 500)) + scale_fill_manual(values = c("white", "red")) + guides(fill=FALSE)
# Statistical test
t.test(Vg4.Th1[Vg4.Th1$Age == "young","Inv_Simps"],
       Vg4.Th1[Vg4.Th1$Age == "old","Inv_Simps"])

inv.simps.list[["TRD_Vg4_Th1"]] <- Vg4.Th1
```

### Vg4 Th17

```{r}
cur_files <- TRD.files[grepl("Vg4_Th17-", TRD.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRD.files[grepl("Vg4_Th17-", TRD.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg4.Th17 <- data.frame(inv.Simps(cur_files, cur_names, 
                                subsample = TRUE))
colnames(Vg4.Th17) <- "Inv_Simps"
Vg4.Th17$Age <- factor(sapply(rownames(Vg4.Th17), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg4.Th17$Replicate <- c(1:4, 1:6)

# Plot results
p.Vg4.Th17.delta <- ggplot(Vg4.Th17) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 500)) + scale_fill_manual(values = c("white", "red")) + guides(fill=FALSE)
# Statistical test
t.test(Vg4.Th17[Vg4.Th17$Age == "young","Inv_Simps"],
       Vg4.Th17[Vg4.Th17$Age == "old","Inv_Simps"])

inv.simps.list[["TRD_Vg4_Th17"]] <- Vg4.Th17
```

### Vg6 Th17

```{r}
cur_files <- TRD.files[grepl("Vg6_Th17-", TRD.files)]
cur_names <- paste(sub("_unk.*$", "", 
                 substring(TRD.files[grepl("Vg6_Th17-", TRD.files)], 107)), "-",
                 1:length(cur_files), sep = "")
cur_files <- cur_files[order(cur_names)]
cur_names <- cur_names[order(cur_names)]

# Calculate inverse simpsons index
# Inverse Simpsons index
Vg6.Th17 <- data.frame(inv.Simps(cur_files, cur_names, 
                                subsample = TRUE))
colnames(Vg6.Th17) <- "Inv_Simps"
Vg6.Th17$Age <- factor(sapply(rownames(Vg6.Th17), 
                             function(n){unlist(strsplit(n, "-"))[2]}),
                      levels = c("young", "old"))
Vg6.Th17$Replicate <- c(1:6, 1:4)

# Plot results
p.Vg6.Th17.delta <- ggplot(Vg6.Th17) + geom_boxplot(aes(Age, Inv_Simps, fill = Age)) + 
  ylim(c(0, 4)) + scale_fill_manual(values = c("white", "red"))
# Statistical test
t.test(Vg6.Th17[Vg6.Th17$Age == "young","Inv_Simps"],
       Vg6.Th17[Vg6.Th17$Age == "old","Inv_Simps"])

# Save in list
inv.simps.list[["TRD_Vg6_Th17"]] <- Vg6.Th17
write.xlsx(inv.simps.list, "../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_4/InvSimps.xlsx")
```

# Delta chain usage

## V gamma 1 cells

```{r}
# Save results in list
delta.chain.usage <- list()

# Select gamma chain file for young V gamma 1 cells
Vg1.y <- chain.prop(all.files, keywords = c("Vg1", "young", "TRD"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg1.y <- Vg1.y[!apply(Vg1.y, 1, function(n){all(n < 0.01)}),]

# Select gamma chain file for old V gamma 1 cells
Vg1.o <- chain.prop(all.files, keywords = c("Vg1", "old", "TRD"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg1.o <- Vg1.o[!apply(Vg1.o, 1, function(n){all(n < 0.01)}),]

# Plot results
df.melt <- rbind(melt(as.data.frame(t(Vg1.y))), melt(as.data.frame(t(Vg1.o))))
df.melt$Age <- factor(c(rep("Young", nrow(Vg1.y)*ncol(Vg1.y)), 
                 rep("Old", nrow(Vg1.o)*ncol(Vg1.o))), levels = c("Young", "Old"))

# Add addition chains and set value to 0
non.contained <- paste("Vd", 1:12, sep = "")[is.na(match(paste("Vd", 1:12, sep = ""),
                                                         unique(df.melt$variable)))]

df.melt <- rbind(df.melt,
                 data.frame(variable = rep(non.contained, each = 2),
                            value = rep(0, length(non.contained)*2),
                            Age = rep(c("Young", "Old"), length(non.contained))))

p.Vg1.delta.usage <- ggplot(df.melt, aes(factor(variable,
            levels = paste("Vd", 1:12, sep = "")), 
            value*100, fill = Age)) + 
  geom_boxplot() + ylim(c(0,100)) + 
  theme(axis.title = element_text(size = 12), 
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Gamma chain") + ylab("Chain fraction %") + ggtitle("Vg1 delta chain usage") +
  scale_fill_manual(values = c("white", "red"))

# Statistical testing
stats.out <- matrix(data = NA, ncol = 2, nrow = length(unique(df.melt$variable)))
rownames(stats.out) <- unique(df.melt$variable)
colnames(stats.out) <- c("p.value", "adjusted")

for(i in rownames(stats.out)){
  if(sum(df.melt$variable == i & df.melt$Age == "Young") > 1 &
     sum(df.melt$variable == i & df.melt$Age == "Old") > 1){
    cur_test <- t.test(df.melt$value[df.melt$variable == i & df.melt$Age == "Young"],
                       df.melt$value[df.melt$variable == i & df.melt$Age == "Old"])
    stats.out[i,1] <- cur_test$p.value
  }
}

# Multiple testing correction
stats.out[!is.na(stats.out[,1]),2] <- p.adjust(stats.out[!is.na(stats.out[,1]),1],
                                               method = "BH")
stats.out

# Save in list 
delta.chain.usage[["Vg1_Th1"]] <- df.melt
```

## V gamma 4 cells Th1 primed

```{r}
# Select gamma chain file for young V gamma 1 cells
Vg4.y.Th1 <- chain.prop(all.files, keywords = c("Vg4", "young", "TRD", "Th1-"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg4.y.Th1 <- Vg4.y.Th1[!apply(Vg4.y.Th1, 1, function(n){all(n < 0.01)}),]

# Select gamma chain file for old V gamma 1 cells
Vg4.o.Th1 <- chain.prop(all.files, keywords = c("Vg4", "old", "TRD", "Th1-"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg4.o.Th1 <- Vg4.o.Th1[!apply(Vg4.o.Th1, 1, function(n){all(n < 0.01)}),]

# Plot results
df.melt <- rbind(melt(as.data.frame(t(Vg4.y.Th1))), melt(as.data.frame(t(Vg4.o.Th1))))
df.melt$Age <- factor(c(rep("Young", nrow(Vg4.y.Th1)*ncol(Vg4.y.Th1)), 
                 rep("Old", nrow(Vg4.o.Th1)*ncol(Vg4.o.Th1))), levels = c("Young", "Old"))

# Add addition chains and set value to 0
non.contained <- paste("Vd", 1:12, sep = "")[is.na(match(paste("Vd", 1:12, sep = ""),
                                                         unique(df.melt$variable)))]

df.melt <- rbind(df.melt,
                 data.frame(variable = rep(non.contained, each = 2),
                            value = rep(0, length(non.contained)*2),
                            Age = rep(c("Young", "Old"), length(non.contained))))

p.Vg4.Th1.delta.usage <- ggplot(df.melt, aes(factor(variable,
            levels = paste("Vd", 1:12, sep = "")), 
            value*100, fill = Age)) + 
  geom_boxplot() + ylim(c(0,100)) + 
  theme(axis.title = element_text(size = 12), 
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Gamma chain") + ylab("Chain fraction %") + ggtitle("Vg4 Th1 delta chain usage") +
  scale_fill_manual(values = c("white", "red"))

# Statistical testing
stats.out <- matrix(data = NA, ncol = 2, nrow = length(unique(df.melt$variable)))
rownames(stats.out) <- unique(df.melt$variable)
colnames(stats.out) <- c("p.value", "adjusted")

for(i in rownames(stats.out)){
  if(sum(df.melt$variable == i & df.melt$Age == "Young") > 1 &
     sum(df.melt$variable == i & df.melt$Age == "Old") > 1){
    cur_test <- t.test(df.melt$value[df.melt$variable == i & df.melt$Age == "Young"],
                       df.melt$value[df.melt$variable == i & df.melt$Age == "Old"])
    stats.out[i,1] <- cur_test$p.value
  }
}

# Multiple testing correction
stats.out[!is.na(stats.out[,1]),2] <- p.adjust(stats.out[!is.na(stats.out[,1]),1],
                                               method = "BH")
stats.out

# Save in list 
delta.chain.usage[["Vg4_Th1"]] <- df.melt
```

## V gamma 4 cells Th17 primed

```{r}
# Select gamma chain file for young V gamma 1 cells
Vg4.y.Th17 <- chain.prop(all.files, keywords = c("Vg4", "young", "TRD", "Th17-"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg4.y.Th17 <- Vg4.y.Th17[!apply(Vg4.y.Th17, 1, function(n){all(n < 0.01)}),]

# Select gamma chain file for old V gamma 1 cells
Vg4.o.Th17 <- chain.prop(all.files, keywords = c("Vg4", "old", "TRD", "Th17-"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg4.o.Th17 <- Vg4.o.Th17[!apply(Vg4.o.Th17, 1, function(n){all(n < 0.01)}),]

# Plot results
df.melt <- rbind(melt(as.data.frame(t(Vg4.y.Th17))), melt(as.data.frame(t(Vg4.o.Th17))))
df.melt$Age <- factor(c(rep("Young", nrow(Vg4.y.Th17)*ncol(Vg4.y.Th17)), 
                 rep("Old", nrow(Vg4.o.Th17)*ncol(Vg4.o.Th17))), levels = c("Young", "Old"))

# Add addition chains and set value to 0
non.contained <- paste("Vd", 1:12, sep = "")[is.na(match(paste("Vd", 1:12, sep = ""),
                                                         unique(df.melt$variable)))]

df.melt <- rbind(df.melt,
                 data.frame(variable = rep(non.contained, each = 2),
                            value = rep(0, length(non.contained)*2),
                            Age = rep(c("Young", "Old"), length(non.contained))))

p.Vg4.Th17.delta.usage <- ggplot(df.melt, aes(factor(variable,
            levels = paste("Vd", 1:12, sep = "")), 
            value*100, fill = Age)) + 
  geom_boxplot() + ylim(c(0,100)) + 
  theme(axis.title = element_text(size = 12), 
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Gamma chain") + ylab("Chain fraction %") + ggtitle("Vg4 Th17 delta chain usage") +
  scale_fill_manual(values = c("white", "red"))

# Statistical testing
stats.out <- matrix(data = NA, ncol = 2, nrow = length(unique(df.melt$variable)))
rownames(stats.out) <- unique(df.melt$variable)
colnames(stats.out) <- c("p.value", "adjusted")

for(i in rownames(stats.out)){
  if(sum(df.melt$variable == i & df.melt$Age == "Young") > 1 &
     sum(df.melt$variable == i & df.melt$Age == "Old") > 1){
    cur_test <- t.test(df.melt$value[df.melt$variable == i & df.melt$Age == "Young"],
                       df.melt$value[df.melt$variable == i & df.melt$Age == "Old"])
    stats.out[i,1] <- cur_test$p.value
  }
}

# Multiple testing correction
stats.out[!is.na(stats.out[,1]),2] <- p.adjust(stats.out[!is.na(stats.out[,1]),1],
                                               method = "BH")
stats.out

# Save in list 
delta.chain.usage[["Vg4_Th17"]] <- df.melt
```

## V gamma 6 cells

```{r}
# Select gamma chain file for young V gamma 1 cells
Vg6.y <- chain.prop(all.files, keywords = c("Vg6", "young", "TRD"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg6.y <- Vg6.y[!apply(Vg6.y, 1, function(n){all(n < 0.01)}),]

# Select gamma chain file for old V gamma 1 cells
Vg6.o <- chain.prop(all.files, keywords = c("Vg6", "old", "TRD"),
                       annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Remove clones that are not detected in with 1% in one of the libraries
Vg6.o <- Vg6.o[!apply(Vg6.o, 1, function(n){all(n < 0.01)}),]

# Plot results
df.melt <- rbind(melt(as.data.frame(t(Vg6.y))), melt(as.data.frame(t(Vg6.o))))
df.melt$Age <- factor(c(rep("Young", nrow(Vg6.y)*ncol(Vg6.y)), 
                 rep("Old", nrow(Vg6.o)*ncol(Vg6.o))), levels = c("Young", "Old"))

# Add addition chains and set value to 0
non.contained <- paste("Vd", 1:12, sep = "")[is.na(match(paste("Vd", 1:12, sep = ""),
                                                         unique(df.melt$variable)))]

df.melt <- rbind(df.melt,
                 data.frame(variable = rep(non.contained, each = 2),
                            value = rep(0, length(non.contained)*2),
                            Age = rep(c("Young", "Old"), length(non.contained))))

p.Vg6.delta.usage <- ggplot(df.melt, aes(factor(variable,
            levels = paste("Vd", 1:12, sep = "")), 
            value*100, fill = Age)) + 
  geom_boxplot() + ylim(c(0,100)) + 
  theme(axis.title = element_text(size = 12), 
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Gamma chain") + ylab("Chain fraction %") + ggtitle("Vg6 delta chain usage") +
  scale_fill_manual(values = c("white", "red"))

# Statistical testing
stats.out <- matrix(data = NA, ncol = 2, nrow = length(unique(df.melt$variable)))
rownames(stats.out) <- unique(df.melt$variable)
colnames(stats.out) <- c("p.value", "adjusted")

for(i in rownames(stats.out)){
  if(sum(df.melt$variable == i & df.melt$Age == "Young") > 1 &
     sum(df.melt$variable == i & df.melt$Age == "Old") > 1){
    cur_test <- t.test(df.melt$value[df.melt$variable == i & df.melt$Age == "Young"],
                       df.melt$value[df.melt$variable == i & df.melt$Age == "Old"])
    stats.out[i,1] <- cur_test$p.value
  }
}

# Multiple testing correction
stats.out[!is.na(stats.out[,1]),2] <- p.adjust(stats.out[!is.na(stats.out[,1]),1],
                                               method = "BH")
stats.out

# Save in list 
delta.chain.usage[["Vg6_Th17"]] <- df.melt

write.xlsx(delta.chain.usage, "../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_4/DeltaChainUsage.xlsx")
```

# Clonal expansion

```{r}
# Select top 10 clones in old and young for each Vg4 Th17 library 
Vg4_Th17_old_TRD <- topCDR3(all.files, top = 10, 
                            keywords = c("Vg4", "old", "TRD", "Th17-"),
                            annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))
Vg4_Th17_young_TRD <- topCDR3(all.files, top = 10, 
                            keywords = c("Vg4", "young", "TRD", "Th17-"),
                            annotation = data.frame(row.names = rownames(annot),
                                               annotation = annot[,"IMGT sub-group"]))

# Visualize clones
# Merge clones
cur_clones <- data.frame(na = unique(c(Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na)),
                         aa = c(Vg4_Th17_old_TRD$aa,
                                Vg4_Th17_young_TRD$aa)[
                           match(unique(c(Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na)),
                                 c(Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na))
                         ],
                         chain = c(Vg4_Th17_old_TRD$chain,
                                Vg4_Th17_young_TRD$chain)[
                           match(unique(c(Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na)),
                                 c(Vg4_Th17_old_TRD$na,
                                       Vg4_Th17_young_TRD$na))
                         ])
rownames(cur_clones) <- cur_clones$na

c.names <- c(paste("Vg4_Th17-_young_TRD_X", 
                   1:sum(grepl("Vg4_Th17-young", TRD.files)), 
                   sep =  "_"),
             paste("Vg4_Th17-_old_TRD_X", 
                   1:sum(grepl("Vg4_Th17-old", TRD.files)), 
                   sep =  "_"))
cur_mat <- matrix(data = NA, ncol = length(c.names), 
              nrow = nrow(cur_clones))
colnames(cur_mat) <- c.names
rownames(cur_mat) <- cur_clones$na

for(i in c.names){
  cur_mat[,i] <- clones.fraction(all.files, i, cur_clones$na)
}
cur_mat <- cur_mat[order(rowMeans(cur_mat), decreasing = TRUE),]
rownames(cur_mat) <- paste(cur_clones[rownames(cur_mat),"na"],
                           cur_clones[rownames(cur_mat),"aa"], sep = ", ")

# Generate annotation data.frame
annot.df <- data.frame(row.names = rownames(cur_mat),
                       chain = cur_clones[sub(", [A-Z]*$", "", 
                                              rownames(cur_mat)),
                                          "chain"])

# Select most enriched clones > 5%
cur_mat.vis <- cur_mat[apply(cur_mat, 1, max) > 0.05,]
cur_mat.vis <- cur_mat.vis[order(annot.df[rownames(cur_mat.vis),"chain"],
                                 rowMeans(cur_mat.vis)),]
cur_mat.vis <- cur_mat.vis[annot.df[rownames(cur_mat.vis),"chain"] == "Vd2" |
                             annot.df[rownames(cur_mat.vis),"chain"] == "Vd5",]


# Visualize in form of heatmap
pdf("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Figures/Figure_4/Heatmap.pdf", 
    onefile = FALSE, width = 25, height = 10)
print(pheatmap(cur_mat.vis, 
         color = c("white", colorRampPalette(c("grey", "blue", "red"))(9999)),
         cluster_cols = FALSE, cluster_rows = FALSE, 
         breaks = seq(0, max(cur_mat), length.out = 10000), 
         fontsize = 8,
         annotation_row = annot.df,
         gaps_row = c(10), gaps_col = c(6), 
         border_color = "black", cellwidth = 20, cellheight = 20, 
         display_numbers = TRUE, fontsize_number = 8, number_color = "black"))
dev.off()
```

# Dot plot of D5 clone

```{r}
cur_size <- melt(tail(cur_mat.vis, 1))
cur_size$Age <- factor(c(rep("Young", 6), rep("Old", 4)),
                       levels = c("Young", "Old"))

write.xlsx(cur_size, "../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_4/CASGYIGGIRATDKLVF_clone.xlsx")

p.clone <- ggplot(cur_size) + 
  geom_boxplot(aes(Age, value*100, fill = Age), width = 0.5) + 
  geom_jitter(aes(Age, value*100, fill = Age), shape = 21, size = 5, width = 0.1) +
  scale_fill_manual(values = c("white", "red")) +
  ylim(c(0,30)) + ylab("Clone fraction [%]")

t.test(cur_size$value[cur_size$Age == "Old"],
       cur_size$value[cur_size$Age == "Young"])
```


# Save figure

```{r}
final.1 <- plot_grid(p.Vg1.Th1.gamma, p.Vg4.Th1.gamma, p.Vg4.Th17.gamma, p.Vg6.Th17.gamma, 
                     p.Vg1.Th1.delta, p.Vg4.Th1.delta, p.Vg4.Th17.delta, p.Vg6.Th17.delta, 
                     nrow = 1)
final.2 <- plot_grid(p.Vg1.delta.usage, p.Vg4.Th1.delta.usage,
                     p.Vg4.Th17.delta.usage, p.Vg6.delta.usage, ncol = 2,
                     nrow = 2)
final.3 <- plot_grid(p.clone, NULL, NULL, NULL, nrow = 1)

final <- plot_grid(final.1, final.2, final.3, ncol = 1, rel_heights = c(1,2,1))

ggsave("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_4/Fig_4.pdf", final,
       width = 15, height = 15)
```