---
title: "Figure 3"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data and libraries

```{r libraries, message=FALSE}
library(cowplot)
library(edgeR)
library(pheatmap)
library(viridis)
library(openxlsx)
```

```{r data}
# Raw counts
raw <- read.table("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Data/FilteredCounts.txt", sep = "\t")

# Normalized counts
norm <- read.table("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Data/NormCounts.txt", sep = "\t")

# Load marker genes for T cells
marker <- read.csv("/Users/nils/Dropbox (Cambridge University)/GammaDelta/Analysis/Data/Genelist.csv", stringsAsFactors = FALSE)
marker <- marker[marker[,1] != '',]
marker <- marker[grepl("ENS", marker$Ensembl.ID),]
rownames(marker) <- marker$Ensembl.ID

# Read in genenames
names <- read.table("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/Genenames.txt", sep = "\t")
rownames(names) <- names$V1
```

# Plot target genes of Il7 signalling

Here, we visualize target genes of Il7 signalling and compute an "activation" score.

```{r Il7-genes}
genes <- c("Bcl2", "Crebbp", "Ep300", "Fyn", "Il2rg", "Il7", "Il7r", 
           "Jak1", "Jak3", "Lck", "Nmi",
           "Pik3ca", "Pik3cg", "Pik3r1", "Ptk2b", "Stat5a", "Stat5b")

for.heatmap <- norm[rownames(names)[match(genes, names$V2)],order(colnames(norm))]

pdf("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/Il7_Heatmap.pdf",
    width = 10, height = 7)
pheatmap(log10(for.heatmap + 1), 
         cluster_cols = FALSE, cluster_rows = FALSE, 
         labels_row = genes, 
         show_colnames = FALSE,
         cellheight = 12, fontsize = 10, color = viridis(100),
         annotation_col = data.frame(row.names = colnames(for.heatmap),
                      condition = sub("_DO.+$", "", colnames(for.heatmap))))
dev.off()

# Calculate averaged Z score
for.heatmap.z <- t(apply(log(for.heatmap + 1), 1, function(n){(n-mean(n))/sd(n)}))
plot(colMeans(for.heatmap.z))

c <- ggplot(data.frame(Il7_score = colMeans(for.heatmap.z),
                  condition = sub("_DO[0-9]*$", "", colnames(for.heatmap.z)))) +
  geom_boxplot(aes(condition, Il7_score))
ggsave("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/Il7_score_boxplot.pdf", 
       Il7_boxplot, width = 12)

# Statistical testing
# Vg1 Th1
t.test(colMeans(for.heatmap.z)[grepl("Vg1_Th1_young", colnames(for.heatmap.z))],
       colMeans(for.heatmap.z)[grepl("Vg1_Th1_old", colnames(for.heatmap.z))])
t.test(colMeans(for.heatmap.z)[grepl("Vg4_Th1_young", colnames(for.heatmap.z))],
       colMeans(for.heatmap.z)[grepl("Vg4_Th1_old", colnames(for.heatmap.z))])
t.test(colMeans(for.heatmap.z)[grepl("Vg4_Th17_young", colnames(for.heatmap.z))],
       colMeans(for.heatmap.z)[grepl("Vg4_Th17_old", colnames(for.heatmap.z))])
t.test(colMeans(for.heatmap.z)[grepl("Vg6_Th17_young", colnames(for.heatmap.z))],
       colMeans(for.heatmap.z)[grepl("Vg6_Th17_old", colnames(for.heatmap.z))])
```

# Plot marker genes

```{r marker-genes}
for.heatmap <- norm[,order(colnames(norm))]

# Select genes of interest
genes <- c("Sell", "Ccr7", "Cxcr3", "Ptprc", "Cd27", "Ccl5", "Il2rb", "Relb", 
           "Id2", "Id3", "Tbx21", "Eomes", "Cd44", "Il7r", "Il1r1", "Il23r",
           "Cd163l1", "Ccr2", "Ccr6", "Blk", "Rorc", "Sox13", "Maf",
           "Lingo4", "Zbtb7b", "Tcf7", "Itk", "Bcl11b")
for.heatmap <- for.heatmap[rownames(names)[match(genes, names$V2)],]

pdf("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/Heatmap.pdf",
    width = 10, height = 15)
pheatmap(log10(for.heatmap + 1), 
         cluster_cols = FALSE, cluster_rows = FALSE, 
         labels_row = genes, 
         show_colnames = FALSE,
         cellheight = 8, fontsize = 7, color = viridis(100),
         annotation_col = data.frame(row.names = colnames(for.heatmap),
                      condition = sub("_DO.+$", "", colnames(for.heatmap))))
dev.off()
```

# Plot PCA of libraries

```{r pca}
pca <- prcomp(t(log10(norm + 1)))

# Variance explained pca
(pca$sdev^2)/sum(pca$sdev^2)

# Only the young libraries
PC12.young <- ggplot(data.frame(condition = sub("_DO.+$", "", colnames(norm)[!grepl("old", colnames(norm))]),
                  PC1 = pca$x[!grepl("old", colnames(norm)),1],
                  PC2 = pca$x[!grepl("old", colnames(norm)),2])) +
  geom_point(aes(PC1, PC2, fill = condition), shape = 21, size = 2) + 
  scale_fill_brewer(palette = "Set1") + guides(fill = FALSE) + ylim(c(-20, 50)) +
  xlim(c(-30, 30))
ggsave("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/PCA_young.pdf", PC12.young,
       width = 4, height = 4)

# Now only the old
PC12.old <- ggplot(data.frame(condition = sub("_DO.+$", "", colnames(norm)[grepl("old", colnames(norm))]),
                  PC1 = pca$x[grepl("old", colnames(norm)),1],
                  PC2 = pca$x[grepl("old", colnames(norm)),2])) +
  geom_point(aes(PC1, PC2, fill = condition), shape = 21, size = 2) + 
  scale_fill_brewer(palette = "Set1") + ylim(c(-20, 50)) +
  xlim(c(-30, 30)) + guides(fill = FALSE)
ggsave("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/PCA_old.pdf", PC12.old,
       width = 4, height = 4)

PC12.old.wGuides <- ggplot(data.frame(condition = sub("_DO.+$", "", colnames(norm)[grepl("old", colnames(norm))]),
                  PC1 = pca$x[grepl("old", colnames(norm)),1],
                  PC2 = pca$x[grepl("old", colnames(norm)),2])) +
  geom_point(aes(PC1, PC2, fill = condition), shape = 21, size = 2) + 
  scale_fill_brewer(palette = "Set1") + ylim(c(-20, 50)) +
  xlim(c(-30, 30))
ggsave("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/PCA_old_withGuides.pdf", PC12.old.wGuides,
       width = 4, height = 4)

# Save pca
write.xlsx(data.frame(names = sub("_DO.+$", "", colnames(norm)), pca$x), "../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/pca.xlsx")
```

# Differential expression analysis

## Vg1

```{r DE}
# Save genes in list
cur_list <- list()
cur_data <- raw[,grepl("Vg1", colnames(raw))]

# Remove lowly expressed genes
cur_data <- cur_data[rowMeans(cur_data) > 10,]
cur_groups <- sapply(colnames(cur_data), function(n){unlist(strsplit(n, "_"))[3]})

# Differential expression analysis
y <- DGEList(counts=cur_data,
             group=cur_groups)
y <- calcNormFactors(y)
design <- model.matrix(~0+y$samples$group)
colnames(design) <- c("Old", "Young")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmQLFTest(fit,coef=2, 
                contrast = makeContrasts(Old - Young, 
                                         levels = design))
cur_res_all <- topTags(qlf, n = nrow(qlf$table))$table

# Visualize results
cur_data <- data.frame(logFC = cur_res_all$logFC,
                  mean = cur_res_all$logCPM,
                  results = ifelse(cur_res_all$logFC > 0 & 
                                     cur_res_all$FDR < 0.1, "Old",
                                   ifelse(cur_res_all$logFC < 0 & 
                                     cur_res_all$FDR < 0.1, "Young", "Not DE")),
                  genenames = names[rownames(cur_res_all),2])

p.Vg1 <- ggplot(cur_data) +
  geom_point(aes(mean, logFC, colour = results, size = results)) + 
  geom_label(data = cur_data[cur_data$results != "Not DE",],
             aes(mean, logFC, label = genenames), hjust = 0, nudge_x = 0.5) + 
  scale_color_manual(values = c("grey", "dark red", "dark blue")) +
  scale_size_manual(values = c(0.5, 2, 2)) + ylim(c(-10,10)) + 
  ggtitle("Vg1")

cur_res_all <- cur_res_all[cur_res_all$FDR < 0.1,]
cur_res_all$Symbol <- names[rownames(cur_res_all),2]
cur_res_all$Directionality <- ifelse(cur_res_all$logFC > 0, "Up in old", 
                                     "Up in young")
cur_list[["Vg1 Th1"]] <- cur_res_all
```


## Vg4 Th1

```{r DE}
cur_data <- raw[,grepl("Vg4_Th1_", colnames(raw))]

# Remove lowly expressed genes
cur_data <- cur_data[rowMeans(cur_data) > 10,]
cur_groups <- sapply(colnames(cur_data), function(n){unlist(strsplit(n, "_"))[3]})

# Differential expression analysis
y <- DGEList(counts=cur_data,
             group=cur_groups)
y <- calcNormFactors(y)
design <- model.matrix(~0+y$samples$group)
colnames(design) <- c("Old", "Young")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmQLFTest(fit,coef=2, 
                contrast = makeContrasts(Old - Young, 
                                         levels = design))
cur_res_all <- topTags(qlf, n = nrow(qlf$table))$table

# Visualize results
cur_data <- data.frame(logFC = cur_res_all$logFC,
                  mean = cur_res_all$logCPM,
                  results = ifelse(cur_res_all$logFC > 0 & 
                                     cur_res_all$FDR < 0.1, "Old",
                                   ifelse(cur_res_all$logFC < 0 & 
                                     cur_res_all$FDR < 0.1, "Young", "Not DE")),
                  genenames = names[rownames(cur_res_all),2])

p.Vg4_Th1 <- ggplot(cur_data) +
  geom_point(aes(mean, logFC, colour = results, size = results)) + 
  geom_label(data = cur_data[cur_data$results != "Not DE",],
             aes(mean, logFC, label = genenames), hjust = 0, nudge_x = 0.5) + 
  scale_color_manual(values = c("grey", "dark red", "dark blue")) +
  scale_size_manual(values = c(0.5, 2, 2)) + ylim(c(-10,10)) + 
  ggtitle("Vg4 Th1")

cur_res_all <- cur_res_all[cur_res_all$FDR < 0.1,]
cur_res_all$Symbol <- names[rownames(cur_res_all),2]
cur_res_all$Directionality <- ifelse(cur_res_all$logFC > 0, "Up in old", 
                                     "Up in young")
cur_list[["Vg4 Th1"]] <- cur_res_all
```

## Vg4 Th17

```{r DE}
cur_data <- raw[,grepl("Vg4_Th17_", colnames(raw))]

# Remove lowly expressed genes
cur_data <- cur_data[rowMeans(cur_data) > 10,]
cur_groups <- sapply(colnames(cur_data), function(n){unlist(strsplit(n, "_"))[3]})

# Differential expression analysis
y <- DGEList(counts=cur_data,
             group=cur_groups)
y <- calcNormFactors(y)
design <- model.matrix(~0+y$samples$group)
colnames(design) <- c("Old", "Young")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmQLFTest(fit,coef=2, 
                contrast = makeContrasts(Old - Young, 
                                         levels = design))
cur_res_all <- topTags(qlf, n = nrow(qlf$table))$table

# Visualize results
cur_data <- data.frame(logFC = cur_res_all$logFC,
                  mean = cur_res_all$logCPM,
                  results = ifelse(cur_res_all$logFC > 0 & 
                                     cur_res_all$FDR < 0.1, "Old",
                                   ifelse(cur_res_all$logFC < 0 & 
                                     cur_res_all$FDR < 0.1, "Young", "Not DE")),
                  genenames = names[rownames(cur_res_all),2])

p.Vg4_Th17 <- ggplot(cur_data) +
  geom_point(aes(mean, logFC, colour = results, size = results)) + 
  geom_label(data = cur_data[cur_data$results != "Not DE",],
             aes(mean, logFC, label = genenames), hjust = 0, nudge_x = 0.5) + 
  scale_color_manual(values = c("grey", "dark red", "dark blue")) +
  scale_size_manual(values = c(0.5, 2, 2)) + ylim(c(-10,10)) + 
  ggtitle("Vg4 Th17")

cur_res_all <- cur_res_all[cur_res_all$FDR < 0.1,]
cur_res_all$Symbol <- names[rownames(cur_res_all),2]
cur_res_all$Directionality <- ifelse(cur_res_all$logFC > 0, "Up in old", 
                                     "Up in young")
cur_list[["Vg4 Th17"]] <- cur_res_all
```

## Vg6 Th17

```{r DE}
cur_data <- raw[,grepl("Vg6", colnames(raw))]

# Remove lowly expressed genes
cur_data <- cur_data[rowMeans(cur_data) > 10,]
cur_groups <- sapply(colnames(cur_data), function(n){unlist(strsplit(n, "_"))[3]})

# Differential expression analysis
y <- DGEList(counts=cur_data,
             group=cur_groups)
y <- calcNormFactors(y)
design <- model.matrix(~0+y$samples$group)
colnames(design) <- c("Old", "Young")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmQLFTest(fit,coef=2, 
                contrast = makeContrasts(Old - Young, 
                                         levels = design))
cur_res_all <- topTags(qlf, n = nrow(qlf$table))$table

# Visualize results
cur_data <- data.frame(logFC = cur_res_all$logFC,
                  mean = cur_res_all$logCPM,
                  results = ifelse(cur_res_all$logFC > 0 & 
                                     cur_res_all$FDR < 0.1, "Old",
                                   ifelse(cur_res_all$logFC < 0 & 
                                     cur_res_all$FDR < 0.1, "Young", "Not DE")),
                  genenames = names[rownames(cur_res_all),2])

p.Vg6 <- ggplot(cur_data) +
  geom_point(aes(mean, logFC, colour = results, size = results)) + 
  geom_label(data = cur_data[cur_data$results != "Not DE",],
             aes(mean, logFC, label = genenames), hjust = 0, nudge_x = 0.5) + 
  scale_color_manual(values = c("grey", "dark red", "dark blue")) +
  scale_size_manual(values = c(0.5, 2, 2)) + ylim(c(-10,10)) + 
  ggtitle("Vg6")

cur_res_all <- cur_res_all[cur_res_all$FDR < 0.1,]
cur_res_all$Symbol <- names[rownames(cur_res_all),2]
cur_res_all$Directionality <- ifelse(cur_res_all$logFC > 0, "Up in old", 
                                     "Up in young")
cur_list[["Vg6 Th17"]] <- cur_res_all

# Save list
write.xlsx(cur_list, "../../../Dropbox (Cambridge University)/Gammadelta T cell aging/2_Figures/Tables/Table_S1_notFinal.xlsx")
```

# Save figure

```{r}
final <- plot_grid(p.Vg1, p.Vg4_Th1, p.Vg4_Th17, p.Vg6, nrow = 1)
ggsave("../../../Dropbox (Cambridge University)/GammaDelta/Figures/Figure_3/DE.pdf", final,
       width = 20, height = 4)
```

# Differential expression testing between gd1 and dg17

```{r}
# List to store results
cur_list <- list()

# Vg4 young - gd1 vs gd17
cur_data <- raw[,grepl("Vg4_Th1_young|Vg4_Th17_young", colnames(raw))]

# Remove lowly expressed genes
cur_data <- cur_data[rowMeans(cur_data) > 10,]
cur_groups <- sapply(colnames(cur_data), function(n){unlist(strsplit(n, "_"))[2]})

# Differential expression analysis
y <- DGEList(counts=cur_data,
             group=cur_groups)
y <- calcNormFactors(y)
design <- model.matrix(~0+y$samples$group)
colnames(design) <- c("Th1", "Th17")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmQLFTest(fit,coef=2, 
                contrast = makeContrasts(Th1 - Th17, 
                                         levels = design))
cur_res_all <- topTags(qlf, n = nrow(qlf$table))$table

cur_res_all <- cur_res_all[cur_res_all$FDR < 0.1,]
cur_res_all$Symbol <- names[rownames(cur_res_all),2]
cur_res_all$ID <- names[rownames(cur_res_all),1]
cur_res_all$Directionality <- ifelse(cur_res_all$logFC > 0, "Up in gd1", 
                                     "Up in gd17")

# Order based on LFC
cur_res_all <- cur_res_all[order(cur_res_all$logFC, decreasing = TRUE),]

cur_list[["Vg4_young_gd1-vs-gd17"]] <- cur_res_all

# Vg4 old - gd1 vs gd17
cur_data <- raw[,grepl("Vg4_Th1_old|Vg4_Th17_old", colnames(raw))]

# Remove lowly expressed genes
cur_data <- cur_data[rowMeans(cur_data) > 10,]
cur_groups <- sapply(colnames(cur_data), function(n){unlist(strsplit(n, "_"))[2]})

# Differential expression analysis
y <- DGEList(counts=cur_data,
             group=cur_groups)
y <- calcNormFactors(y)
design <- model.matrix(~0+y$samples$group)
colnames(design) <- c("Th1", "Th17")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmQLFTest(fit,coef=2, 
                contrast = makeContrasts(Th1 - Th17, 
                                         levels = design))
cur_res_all <- topTags(qlf, n = nrow(qlf$table))$table

cur_res_all <- cur_res_all[cur_res_all$FDR < 0.1,]
cur_res_all$Symbol <- names[rownames(cur_res_all),2]
cur_res_all$ID <- names[rownames(cur_res_all),1]
cur_res_all$Directionality <- ifelse(cur_res_all$logFC > 0, "Up in gd1", 
                                     "Up in gd17")

# Order based on LFC
cur_res_all <- cur_res_all[order(cur_res_all$logFC, decreasing = TRUE),]

cur_list[["Vg4_old_gd1-vs-gd17"]] <- cur_res_all

# All gd1 vs all gd17
cur_data <- raw

# Remove lowly expressed genes
cur_data <- cur_data[rowMeans(cur_data) > 10,]
cur_groups <- sapply(colnames(cur_data), function(n){unlist(strsplit(n, "_"))[2]})

# Differential expression analysis
y <- DGEList(counts=cur_data,
             group=cur_groups)
y <- calcNormFactors(y)
design <- model.matrix(~0+y$samples$group)
colnames(design) <- c("Th1", "Th17")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmQLFTest(fit,coef=2, 
                contrast = makeContrasts(Th1 - Th17, 
                                         levels = design))
cur_res_all <- topTags(qlf, n = nrow(qlf$table))$table

cur_res_all <- cur_res_all[cur_res_all$FDR < 0.1,]
cur_res_all$Symbol <- names[rownames(cur_res_all),2]
cur_res_all$ID <- names[rownames(cur_res_all),1]
cur_res_all$Directionality <- ifelse(cur_res_all$logFC > 0, "Up in gd1", 
                                     "Up in gd17")

# Order based on LFC
cur_res_all <- cur_res_all[order(cur_res_all$logFC, decreasing = TRUE),]

cur_list[["All_gd1-vs-gd17"]] <- cur_res_all

# Save background
write.csv(rownames(cur_data), "../../../Dropbox (Cambridge University)/GammaDelta/Analysis/Results/Th1_Th17_comparison/background_280319.csv", 
          quote = FALSE, row.names = FALSE, col.names = FALSE)

write.xlsx(cur_list, "../../../Dropbox (Cambridge University)/Gammadelta T cell aging/2_Figures/Tables/Table_S2_notFinal.xlsx")
```